# object==>
#student:
#  name: Jack
#  age: 29

# inline==>
#people: {name: Tom, age: 33}

# array==>
#pets:
#  - cat
#  - dog
#  - pig
#
#animals: [cat, dog, horse]

dog:
  name: cheese
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  maps: {k1: v1, k2: v2}
  lists:
    - code
    - music
    - girl
  person:
    name: jack
    age: 31